backend:
  name: git-gateway
  branch: main

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "publication"
    label: "Publications"
    folder: "content/publication"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Authors", name: "authors", widget: "list" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Abstract", name: "abstract", widget: "text" }
      - { label: "Publication", name: "publication", widget: "string" }
      - { label: "DOI", name: "doi", widget: "string", required: false }
      - { label: "Featured", name: "featured", widget: "boolean", default: false }
      - { label: "Body", name: "body", widget: "markdown" }
